spring:

  profiles:
    active:
    - local
  
  mvc:
    view:
      prefix: "/WEB-INF/views"
      suffix: ".jsp"
      
   
  datasource:
    url: jdbc:mysql://15.165.187.225:3306/random?characterEncoding=UTF-8&serverTimezone=UTC
    username: ho  
    password: dmswlsdkwna2@
    driver-class-name: com.mysql.cj.jdbc.Driver
    
  servlet:    multipart:      max-file-size: 10MB
      max-request-size: 20MB        
                     

server:  port: 80
  tomcat:    accesslog:      encoding: UTF-8
   
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  
    
    
 
    jsp:
      init-parameters:        development: true
    session:
      timeout: 7200
  
  error:
    whitelabel:      enabled: false
      
mybatis:
    type-aliases-package: com.hbproject.example.domain
    mapper-locations: mapper/**/*.xml
    

      