spring:

  profiles:
    active:
    - local
  
  mvc:
    view:
      prefix: "/WEB-INF/views"
      suffix: ".jsp"
      
   
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/random?characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 
    driver-class-name: com.mysql.cj.jdbc.Driver
    
  session:
    jdbc:
      initialize-schema: always

server:  port: 80
  tomcat:    accesslog:      encoding: UTF-8
   
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
      
    jsp:
      init-parameters:        development: true
    session:
      timeout: 7200
  
  error:
    whitelabel:      enabled: false
      
mybatis:
    type-aliases-package: com.hbproject.example.domain
    mapper-locations: mapper/**/*.xml
    

      